import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Folder/File Management",
  description: "Generated by create Rajath R Patil",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <script src="https://cdn.tailwindcss.com"></script>
        {children}
      </body>
    </html>
  );
}
